version: "3.8"

services:
  # Налаштування бази даних PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: valorant_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Налаштування твого FastAPI сервера
  web:
    build: .
    container_name: valorant_api
    restart: always
    # Docker автоматично запустить міграції, а потім сам сервер
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app # Це дозволить бачити зміни в коді без перезапуску контейнера
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  # Налаштування Streamlit фронтенду
  # Налаштування Streamlit фронтенду
  frontend:
    build:
      context: ./frontend
    container_name: valorant_frontend
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - web
    environment:
      - BACKEND_URL=http://web:8000

volumes:
  postgres_data: