"""add puuid to players

Revision ID: 2dc894397c5e
Revises: bde2045c15fd
Create Date: 2026-07-09 23:39:32.918031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc894397c5e'
down_revision: Union[str, Sequence[str], None] = 'bde2045c15fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('puuid', sa.String(), nullable=False))
    op.create_index(op.f('ix_players_puuid'), 'players', ['puuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_puuid'), table_name='players')
    op.drop_column('players', 'puuid')
    # ### end Alembic commands ###
